### ISSUE TITLE
GigyaSwift does not compile in Xcode 12 GM (build 12A7209)

### ISSUE THREAD

**Issue by glbgnn** [SAP/gigya-swift-sdk#3]
I'm having the same problem described in issue #1 using Gigya 1.1.3 via Cocoapods, but with the GM build of Xcode 12 (build 12A7209).

As you can see from the compiler stack trace here, [LoginApiError-stacktrace.txt](https://github.com/SAP/gigya-swift-sdk/files/5244348/LoginApiError-stacktrace.txt), the problem seems to originate from line 31 in `GigyaApiResult.swift` and looks to be related to the use of generics.

**Comment by s1180031** [comment]
https://github.com/s1180031/gigya-swift-sdk/pull/1 

The build was successful when the order of the class definitions was changed.

But I don't know why it succeeds...

**Comment by aruffolo** [comment]
> [s1180031#1](https://github.com/s1180031/gigya-swift-sdk/pull/1)
> 
> The build was successful when the order of the class definitions was changed.
> 
> But I don't know why it succeeds...

How did you change the order?

**Comment by s1180031** [comment]
@aruffolo 

> How did you change the order?

I'm moving LoginApiError above GigyaLoginResult.
I was using LoginApiError in GigyaLoginResult and thought it was affecting the compilation.

**Comment by sagishm** [comment]
> GigyaLoginResult

just for note: we are open source, you can make a pull request with your solution.

**Comment by s1180031** [comment]
> just for note: we are open source, you can make a pull request with your solution.

I sent a pull request.　Please validate it.

**Comment by ababeel** [comment]
the issue still happens when creating a build with fastlane, it's the same error that was happening before also with XCode but with the fix it resolved only for XCode

**error:**
`.../Pods/Gigya/GigyaSwift/Global/Resolvers/Tfa/TFAResolverFactory.swift:23:27: type 'T' has no member 'init'`

also, the error is happening in TFA module which we don't use but there's no way to download 'core' only? 

something like `pod 'Gigya/Core'` would be nice to have
